// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgaBaE8SWk6ouM71sZBdt2JkPC5QpWBig',
    appId: '1:655125243696:web:ebc402d7842a655ee70af5',
    messagingSenderId: '655125243696',
    projectId: 'bullseye-dryfire',
    authDomain: 'bullseye-dryfire.firebaseapp.com',
    storageBucket: 'bullseye-dryfire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMzVdHH-3hXg4pY8ysgrsBcgaLjc7g9KE',
    appId: '1:655125243696:android:0ce47a36d99cec18e70af5',
    messagingSenderId: '655125243696',
    projectId: 'bullseye-dryfire',
    storageBucket: 'bullseye-dryfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDQBOUQ2VFayJSP0ujX4pFNXTceNlfNw',
    appId: '1:655125243696:ios:4e3628c8f25cda8ce70af5',
    messagingSenderId: '655125243696',
    projectId: 'bullseye-dryfire',
    storageBucket: 'bullseye-dryfire.firebasestorage.app',
    iosBundleId: 'com.example.bullseyeDryfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDQBOUQ2VFayJSP0ujX4pFNXTceNlfNw',
    appId: '1:655125243696:ios:4e3628c8f25cda8ce70af5',
    messagingSenderId: '655125243696',
    projectId: 'bullseye-dryfire',
    storageBucket: 'bullseye-dryfire.firebasestorage.app',
    iosBundleId: 'com.example.bullseyeDryfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgaBaE8SWk6ouM71sZBdt2JkPC5QpWBig',
    appId: '1:655125243696:web:763859055618f93ce70af5',
    messagingSenderId: '655125243696',
    projectId: 'bullseye-dryfire',
    authDomain: 'bullseye-dryfire.firebaseapp.com',
    storageBucket: 'bullseye-dryfire.firebasestorage.app',
  );
}
